exclude: fixtures/|.gitlab-ci.yml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
        files: ^beauty_be/.*\.py$
      - id: end-of-file-fixer
        exclude: static|README.md|release_notes
        files: ^beauty_be/.*\.py$
      - id: check-docstring-first
        files: ^beauty_be/.*\.py$
      - id: debug-statements
        files: ^beauty_be/.*\.py$
      - id: double-quote-string-fixer
        files: ^beauty_be/.*\.py$
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: [ --line-length=120, -S ]
        files: ^beauty_be/.*\.py$
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-typing-imports
          - flake8-comprehensions
          - flake8-eradicate
          - flake8-spellcheck
          - dlint
          - darglint
          - mccabe
          - pep8-naming
          - flake8-isort
        args:
          - "--max-line-length=120"
          - "--classmethod-decorators=classmethod"
          - "--whitelist=whitelist.txt"
          - "--config=.flake8"
        files: ^beauty_be/.*\.py$
  - repo: local
    hooks:
      - id: mypy
        name: Mypy check
        entry: sh -c 'mypy --config-file=.mypy.ini beauty_be || exit 1'
        language: system
        pass_filenames: false
        files: ^beauty_be/.*\.py$
